# Generated by Django 5.0.2 on 2024-04-06 06:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PARENT',
            fields=[
                ('PARENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('EMAIL_ADDRESS', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT',
            fields=[
                ('STUDENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('EMAIL_ADDRESS', models.CharField(max_length=255, unique=True)),
                ('PARENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.parent')),
            ],
        ),
        migrations.CreateModel(
            name='TEACHER',
            fields=[
                ('TEACHER_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(max_length=255)),
                ('PHONE_NO', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits.', regex='^\\d{10}$')])),
                ('EMAIL_ADDRESS', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='STUDENT_INFO',
            fields=[
                ('STUDENT_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ATS_app.student')),
                ('DEPARTMENT', models.CharField(max_length=255)),
                ('SECTION', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ATTENDANCE_DATA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('FIRST_NAME', models.CharField(max_length=255)),
                ('LAST_NAME', models.CharField(default='', max_length=255)),
                ('DATE', models.DateField()),
                ('HOUR1', models.CharField(default='NULL', max_length=255)),
                ('HOUR2', models.CharField(default='NULL', max_length=255)),
                ('HOUR3', models.CharField(default='NULL', max_length=255)),
                ('HOUR4', models.CharField(default='NULL', max_length=255)),
                ('HOUR5', models.CharField(default='NULL', max_length=255)),
                ('HOUR6', models.CharField(default='NULL', max_length=255)),
                ('HOUR7', models.CharField(default='NULL', max_length=255)),
                ('HOUR8', models.CharField(default='NULL', max_length=255)),
                ('STUDENT_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATS_app.student')),
            ],
        ),
    ]
